### ISSUE TITLE
Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by ameise1** [acidhax/chromecast-audio-stream#115]
Hi,

I get this error message when I start Audio-Cast on Win 10 Pro:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot find module 'express'
at Module._resolveFilename (module.js:438:15)
at Function.Module._resolveFilename (C:\Users\Internet\Downloads\audio-cast-win32-ia32
(1)\audio-cast-win32-ia32\resources\electron.asar\common\reset-search-paths.js:47:12)
at Function.Module._load (module.js:386:25)
at Module.require (module.js:466:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\Users\Internet\Downloads\audio-cast-win32-ia32
(1)\audio-cast-win32-ia32\resources\app.asar\lib.js:5:16)
at Module_compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:456:32)
at tryModuleLoad (module.js:415:12)
```

"C:\Users\Internet\Downloads\audio-cast-win32-ia32(1)\audio-cast-win32-ia32" is an old path, where I first downloaded the tool. Now the tool is stored on "C:\Portable\audio-cast", but for some reason still tries to load modules from the old, no more existing directory.

I tried to clean the registry, move the folder ... without success. How can I get rid from this old path?

**Comment by ameise1** [comment]
I just got it solved. I thoght, the old folder "C:\Users\Internet\Downloads\audio-cast-win32-ia32(1)\audio-cast-win32-ia32" didn't exist anymore. But in fact, it was still there. I deleted the folder, and now Audio-Cast is up and running again.

Thanks a lot for providing this tool. I am enjoying it very much.
