### ISSUE TITLE
java script error

### ISSUE THREAD

**Issue by srouw** [acidhax/chromecast-audio-stream#25]

**Comment by srouw** [comment]
A JavaScript error occured in the main process

Uncaught Exception:
Error: protocol must either "_tcp" or "_udp" but is _dns-sd"
at checkProtocolU
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:11)
at fromString
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:3)
at new exports.ServiceType
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:14)
at
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:25)
at
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:7)
at Array.forEach (native)
at each
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:17)
at module.exports.decodeSection
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:10)
at
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_modules...:5)
at Array.forEach (native)
at Object.module.exports.decodePackets
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:11)
at internal.onMessage
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:22)
at emitThree (events.js:97:13)
at emit (events.js:175:7)
at Socket.<anonymous>
(C:\Users\Scott\Desktop\audio-cast-1.0.0-win32-ia32\resources\app.asar\node_module...:10)
at emitTwo (events.js:87:13)
at Socket.emit (events.js:172:7)
