### ISSUE TITLE
Uncaught Exception: Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by Wegerich** [acidhax/chromecast-audio-stream#93]
I am getting this error on Windows 10 64bit and I don't know why. I have tried running `npm install` in the .exe directory but it didn't help. 

https://i.imgur.com/bIwEcI6.png

```
[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'express'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (C:\Users\Username\Desktop\audio-cast-win32-ia32\resources\electron.asar\common\reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Username\Desktop\audio-cast-win32-ia32\resources\app.asar\lib.js:5:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)

[OK]
```
This is the output from `npm install`

```
npm WARN audio-cast@1.0.0 No description
npm WARN audio-cast@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! audio-cast@1.0.0 postinstall: `grunt ffmpeg_libs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the audio-cast@1.0.0 postinstall script 'grunt ffmpeg_libs'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the audio-cast package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt ffmpeg_libs
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs audio-cast
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls audio-cast
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Username\Desktop\audio-cast-win32-ia32\npm-debug.log
```

**Comment by SamDel** [comment]
I'm not sure what you're trying but it looks like the zip-file was not completely unzipped when you tried to run audio-cast.exe. That's why you got the message about the module `express `that can't be found. 

Can you try again and make sure the file is completely unzipped, and let us know? Or check if the folder `resources\node_modules` contains a subfolder `express` after unzipping?

Running `npm install` in the unzipped folder makes no sense, that command is only for developers after downloading the source code.

**Comment by Wegerich** [comment]
Thank you, I deleted everything and re-extracted and it worked. 

I had no idea if running `npm install` would help but I tried searching for the solution and that was the only thing that came up so I thought I should try it first.
